version: '3.2'

services:
    mysql:
      image: mysql:5.7
      ports:
        - '3306:3306'
      volumes:
      - "/var/lib/mysql"
      restart: always
      environment:
        MYSQL_DATABASE: orders
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
      networks:
        - default
    api:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/app
        - /app/node_modules
      ports:
        - '3333:3333'
      networks:
        - default
      depends_on:
        - mysql
networks:
  default:
    driver: bridge


